exports.CREV_REVIEW_BEGIN = '-----BEGIN CREV PACKAGE REVIEW-----'
exports.CREV_REVIEW_SIG =   '-----BEGIN CREV PACKAGE REVIEW SIGNATURE-----'
exports.CREV_REVIEW_END =   '-----END CREV PACKAGE REVIEW-----'
